### ISSUE TITLE
Consider embedding the SOAP client into controller

### ISSUE THREAD

**Issue by embano1** [cormachogan/hostinfo-operator#1]
Minor resource and performance optimization suggestion (also from VC perspective): Currently, on every `Reconcile()` invocation a new govmomi Client will be created. You might want to consider embedding the Client in the controller, e.g. https://github.com/embano1/codeconnect-vm-operator/blob/main/controllers/vmgroup_controller.go#L51

**Comment by cormachogan** [comment]
Thanks Michael - will take a look at this.
